add_newline = false

format = "$directory$character"
right_format = "$git_branch$git_metrics$nodejs$bun$python$time"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_metrics]
disabled = false
format = "([+$added](bold green) )([-$deleted](bold red) )"

[nodejs]
format = "[ $version](bold green) "

[bun]
format = "[bun $version](bold yellow) "

[python]
format = "[py $version](bold yellow) "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](dimmed white)"